### ISSUE TITLE
Connect to Coveralls.Io

### ISSUE THREAD

**Issue by aik099** [hamcrest/hamcrest-php#10]
It seems, that former https://github.com/cordoval/hamcrest-php had integration with Coveralls.Io service (presence of it's config indicates that).

How about to enable that integration for this repo as well (and remove old one) with adding corresponding badges to README.md?

**Comment by aik099** [comment]
@cordoval , was this done?

**Comment by cordoval** [comment]
I should do this, can you give me friday or do you want to go ahead and do this?

**Comment by aik099** [comment]
> can you give me friday

You mean you'll have time to do this on friday? Sure, no hurry.

**Comment by cordoval** [comment]
so it is configured https://coveralls.io/r/hamcrest/hamcrest-php the thing that we are missing is the https://scrutinizer-ci.com/docs/tools/external-code-coverage/

**Comment by aik099** [comment]
Ah, so the Coveralls.Io integration was there, but we're not posting Coverage Report back to Scrutinizer CI. I see.

That's quite easy to configure but requires changes from both Scrutinizer CI side (to enable external code coverage) and repo side (Travis CI config to send that coverage).

The actual coverage is already being collected for Coveralls.Io.

**Comment by cordoval** [comment]
i have sent scrutinizer support message to see why this is not working cc @schmittjoh

**Comment by cordoval** [comment]
badge is green now https://scrutinizer-ci.com/g/hamcrest/hamcrest-php/?branch=master
