### ISSUE TITLE
Rewrite README.md

### ISSUE THREAD

**Issue by aik099** [hamcrest/hamcrest-php#12]
The way of using Hamcrest (e.g. use `require_once`, include `hamcrest.php`) described in `README.md` doesn't match the way how it works currently.

We already introduced namespaces and Composer auto-loading, so manual assertion class inclusion is no longer needed. I bet there are other non-valid places, that needs to be rewritten.

As @davedevelopment suggested in #8 we might need to remove PEAR section as well.

**Comment by cordoval** [comment]
@davedevelopment can you get us access to pear channel to bring it down? thanks

**Comment by cordoval** [comment]
https://github.com/hamcrest/hamcrest-php/pull/24/files
