### ISSUE TITLE
Migrate to new Travis CI architecture

### ISSUE THREAD

**Issue by aik099** [hamcrest/hamcrest-php#34]
I recommend adding `sudo: false` at the beginning of `.travis.yml` file to make Travis CI use Docker containers for builds, which should speed up build time all together.

Blocked by #33

**Comment by mkasberg** [comment]
Looks like this has already been done? https://github.com/hamcrest/hamcrest-php/commit/be5380f32221c57d4418617738108c5cac5ae78e

**Comment by aik099** [comment]
Yes, indeed. Thanks @mkasberg for finding that.
