### ISSUE TITLE
Improve the Documentation

### ISSUE THREAD

**Issue by ascii-soup** [hamcrest/hamcrest-php#41]
I often recommend Hamcrest to people but a lot of them push back because the documentation isn't very clear/easy to find, and some of them are intimidated by the idea of reading the Java documentation.

I had a conversation with @aik099 over email and he pointed to the PyHamcrest docs (http://pyhamcrest.readthedocs.io/en/latest/tutorial/) as a good example of what could be done here in the PHP port.

It may be possible to simply clone the PyHamcrest docs from github (https://github.com/hamcrest/PyHamcrest/tree/master/doc) and adjust them to reflect PHP syntax, idiosyncrasies and so forth.

I think it would also be a good idea to update the README so that the project has a friendlier github 'home page' and this would be reflected on Packagist also.

Anybody got any thoughts?

**Comment by aik099** [comment]
I've used Hamcrest very briefly inside the Mockery and the only issue I had is a need to go to Hamcrest code to figure out matcher name that needs to be used.

I'm not sure that we need huge documentation (before other ports except Python one doesn't have any), but something simple to get people started surely can be placed in README.

**Comment by garethellis36** [comment]
A list of the included matchers and what they do would be really useful; I have learned how to use most of them by reading the source code which could be intimidating for a beginner.

A basic guide on how to create your own custom matchers would be cool as well.

**Comment by martindilling** [comment]
Just a list of available matchers with their signature would be very helpful, and should be an easy start of better documentation.

And I really think it should be in the readme how you set it up after the package changed to not autoload the Hamcrest.php. I gave up updating to the new version a few times before I figured out why none of the functions worked.

**Comment by aik099** [comment]
@martindilling , better not to use global functions in favor of their static counterparts.

**Comment by ascii-soup** [comment]
I think the global functions are one of Hamcrest's biggest features. It allows very expressive/concise test code.

**Comment by garethellis36** [comment]
Totally agreed, my main reason for using Hamcrest is for having nice expressive code:

`assertThat("foo", is(equalTo("foo")));`

is way nicer than
`assertThat("foo", is(\Hamcrest\Core\IsEqual::equalTo("foo")));

**Comment by aik099** [comment]
> is way nicer than
> `assertThat("foo", \Hamcrest\Core\IsEqual::equalTo("foo"));`

@garethellis36 , this because your code should be:

```php
// the USE statements only once per PHP file
use Hamcrest\Matchers;
use Hamcrest\MatcherAssert;

MatcherAssert::assertThat(
    Matchers::equalTo("foo")
);
```

In short:

* add `MatherAssert::` before any global function you use
* add `MatcherAssert::` before `assertThat` function

**Comment by aik099** [comment]
Yes, in original Hamcrest PHP port there was no such static classes. We've added them to avoid need of using global functions.

**Comment by ascii-soup** [comment]
It's a shame that PHP doesn't have static imports in the same way Java does. However, the documentation could presumably showcase both approaches? It could even say "This is preferred, but if you don't mind polluting your global namespace with functions, you can use these."

**Comment by ascii-soup** [comment]
Also, and again slightly off-topic, Hamcrest could be updated to use namespaced functions if the minimum PHP version was 5.6 (I believe) which could give us the best of both worlds?

**Comment by martindilling** [comment]
@aik099 The expressiveness you get from using the functions is the reason I use hamcrest over phpunit ;)

**Comment by ascii-soup** [comment]
Having come back here for unrelated reasons, I notice the readme has been vastly expanded and now contains lots of useful docs. 👍 👍 👍
