### ISSUE TITLE
Please add a .gitattributes file

### ISSUE THREAD

**Issue by ghost** [hamcrest/hamcrest-php#43]
Please add a `.gitattrubutes` file to exclude the `/tests` directory as well as any other files that are unnecessary in production (e.g.: `TODO.txt`, `CHANGES.txt`)

Thanks :smiley:

**Comment by theofidry** [comment]
@InsaneScripts is that really necessary? This is a package primarily for test purposes and for production surely you run `--no-dev` with Composer

**Comment by reedy** [comment]
Done in #76

**Comment by aik099** [comment]
Fixed in #76.
