### ISSUE TITLE
Removed autoloading of functions?

### ISSUE THREAD

**Issue by mindplay-dk** [hamcrest/hamcrest-php#50]
From `CHANGES.txt`:

```
== Version 2.0: Released XXX XX 2016 ==

* Removed automatic loading of global functions
```

Why?

What's the alternative?

There's no mention in the documentation of how to get this package working - global functions are used everywhere in the `README.md`, and those examples simply don't work.

**Comment by mindplay-dk** [comment]
Okay, so there is *one* example in the README that actually works 🙄

I later discovered `Utils::registerGlobals()` - since that's what the examples rely on, maybe that should at least be mentioned in the README?

**Comment by aik099** [comment]
Sure, you can send a PR with that change.
