### ISSUE TITLE
registerGlobals() or registerGlobalFunctions()? 

### ISSUE THREAD

**Issue by lathspell** [hamcrest/hamcrest-php#52]
The git frontpage README suggest to add `Utils::registerGlobals();` although the method seems to be ` \Hamcrest\Util::registerGlobalFunctions();` as suggested in https://github.com/hamcrest/hamcrest-php/issues/45

**Comment by aik099** [comment]
You're correct. I'm not using global functions myself and therefore I wasn't able to spot that issue in recent #51 PR, where this change was introduced.

Please send a PR with a fix and I'll merge it.

**Comment by lathspell** [comment]
sorry, busy, you may fix your homepage yourself :)

**Comment by aik099** [comment]
Done.
